# Generated by Django 5.2 on 2025-04-25 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, choices=[('neutral', 'Neutral'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('supportive', 'Supportive'), ('romantic', 'Romantic'), ('happy', 'Happy'), ('tense', 'Tense'), ('argumentative', 'Argumentative'), ('angry', 'Angry'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('deep', 'Deep'), ('grateful', 'Grateful'), ('stressed', 'Stressed'), ('hopeful', 'Hopeful')], max_length=20, null=True)),
                ('toxicity_score', models.FloatField(blank=True, null=True)),
                ('ai_suggestion', models.TextField(blank=True, null=True)),
                ('ai_suggestion_used', models.BooleanField(default=False)),
                ('ai_suggestion_feedback', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], max_length=30, null=True)),
                ('summary_tag', models.CharField(blank=True, choices=[('neutral', 'Neutral'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('supportive', 'Supportive'), ('romantic', 'Romantic'), ('happy', 'Happy'), ('tense', 'Tense'), ('argumentative', 'Argumentative'), ('angry', 'Angry'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('deep', 'Deep'), ('grateful', 'Grateful'), ('stressed', 'Stressed'), ('hopeful', 'Hopeful')], max_length=30, null=True)),
                ('source', models.CharField(default='user', max_length=10)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('mood_overview', models.CharField(blank=True, max_length=30, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
            ],
        ),
    ]
